name: Neo
description: Generate a matrix depending on changed files
inputs:
  pattern:
    description: regex pattern with named groups to match against changed files
    required: true
  defaults:
    description: when set to true, if changed files don't match the pattern, recursively match all files in the repository.
    default: "false"
    required: false
  default-patterns:
    description: line separated list of UNIX-style glob patterns matched against the list of changed files. if match, switch to defaults mode.
    default: ""
    required: false
  ignore-deleted-files:
    description: whether to ignore the deleted files or not
    default: "false"
    required: false
  github-token:
    description: token to access the GitHub API
    required: false
    default: '${{ github.token }}'
outputs:
  matrix:
    description: the output job matrix

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    DEFAULT_PATTERNS: ${{ inputs.default-patterns }}
  args:
    - --pattern=${{ inputs.pattern }}
    - --ignore-deleted-files=${{inputs.ignore-deleted-files}}
    - --defaults=${{inputs.defaults}}
branding:
  icon: git-pull-request
  color: green